name: Release
on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Pack & Publish
        run: |
          chmod +x ./build.sh
          ./build.sh Pack Publish --api-key ${{secrets.NUGET_TOKEN}}

      - uses: actions/upload-artifact@v1
        with:
          name: packages
          path: artifacts/packages

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref }} artifacts/packages/*.nupkg
          gh release upload ${{ github.ref }} artifacts/packages/*.snupkg